#!/bin/bash

# Author: Bin Wu <binwu@google.com>

PWD=`pwd`
JAVA=`which java`
#VER=$(<ver)
IPADDR=$(hostname -I | cut -d ' ' -f 1)

__usage() {
    echo "Usage: run {lc|df|clean}"
}

__local() {
    mvn compile exec:java \
        -Dexec.mainClass=bindiego.WordCount \
        -Dexec.args="--output=./output/"
}

__dataflow() {
    mvn -Pdataflow-runner compile exec:java \
        -Dexec.mainClass=bindiego.WordCount \
        -Dexec.args="--project=google.com:bin-wus-learning-center \
        --streaming=false \
        --tempLocation=gs://bindiego/tmp/ \
        --gcpTempLocation=gs://bindiego/tmp/gcp/ \
        --stagingLocation=gs://bindiego/staging/ \
        --runner=DataflowRunner \
        --output=gs://bindiego/output/ \
        --region=asia-east1"
}

__clean() {
    mvn clean; rm -f output-*
}

__geo_db() {
    [ -d geodb ] || mkdir -p $PWD/geodb

    curl https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz \
        > $PWD/geodb/GeoLite2-City.tar.gz
    curl https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz \
        > $PWD/geodb/GeoLite2-Country.tar.gz 

    cd $PWD/geodb

    tar xzf GeoLite2-City.tar.gz; tar xzf GeoLite2-Country.tar.gz
}

__main() {
    if [ $# -eq 0 ]
    then
        __usage
    else
        case $1 in
            lc)
                __local
                ;;
            df)
                __dataflow
                ;;
            clean)
                __clean
                ;;
            geodb)
                __geo_db
                ;;
            *)
                __usage
                ;;
        esac
    fi
}

__main $@

exit 0
